image:
  file: .gitpod.Dockerfile

ports:
  - port: 8080
    onOpen: open-preview

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/44_config_start_tasks/
tasks:
- init: nvm install node && nvm use node
#  command: echo 'start script'

vscode:
  extensions:
    - octref.vetur@0.22.4:yrkjHFQAALg1+saAY4HWdQ==
    - peakchen90.vue-beautify@2.0.4:drPwPJo2Mx92PILu3HZqNQ==
    - dbaeumer.vscode-eslint@1.9.1:YVcwmzKVVl+zZ+wMB02GjQ==
    - pflannery.vscode-versionlens@0.24.0:FzMGwBqMxkIHqADhVK2e2Q==